name: Deploy to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
     - cron:  '0 * * * *'
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job to run Python script and generate content
  generate-content:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Install any dependencies your script might need
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          bash start.sh
      # Run your Python script
      - name: Run Python Script
        run: |
             wget -qq https://stupidfucker79.github.io/Shiny-Scarper/links.txt
             python main.py 
      
      # Create directory for GitHub Pages
      - name: Prepare GitHub Pages directory
        run: |
          mkdir -p generated_pages
          mv links.txt generated_pages/ 
      
      # Upload the 
      # Upload the generated content as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './generated_pages'  # Directory where your script generates content

  # Job to deploy to GitHub Pages
  deploy-to-pages:
    needs: generate-content
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
