name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job to run Python script and generate content
  generate-content:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Building Image
        run: docker build -t bot .
      - name: Running Container
        run: docker run --name GenBot bot
      - name: Copy File from Container
        run: mkdir -p generated_pages
             docker cp GenBot:links.txt ./generated_pages/
      - name: Remove Container
        run: docker rm GenBot  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './generated_pages'  # Directory where your script generates content

  deploy-to-pages:
    needs: generate-content
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
